### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by tbhi** [aberdeen-services/mediainfo-java-api#1]
Hi, could you clarify the license here?  filebot appears to be GPLv3 but https://github.com/aberdeen-services/mediainfo-java-api/blob/master/pom.xml says MIT license.

Thanks

**Comment by andersonkyle** [comment]
@stan3 I see they've added that license file now but it wasn't there when I forked their repository.  You can check the commit history on that file.  Since no license was apparent, I chose the most open license, being MIT.  I'm happy to adjust this repo accordingly.  Are you a contributor to filebot?

**Comment by tbhi** [comment]
Hi, no, just interested in using the library and wanted to clarify the license.
